
modLoader="javafml" #mandatory
loaderVersion="[32,)" #mandatory
license="All rights reserved"
issueTrackerURL="https://github.com/NovaMachina-Mods/ExNihiloSequentia-AE2/issues" #optional
[[mods]] #mandatory
modId="exnihiloae" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Ex Nihilo: Sequentia - AE2 Addon" #mandatory
updateJSONURL="https://raw.githubusercontent.com/NovaMachina-Mods/ExNihiloSequentia-AE/1.16.X/update.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/ex-nihilo-sequentia-ae2-addon/" #optional
logoFile="" #optional
credits="" #optional
authors="NovaMachina" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
An addon for Ex Nihilo: Sequentia that adds support for Applied Energistics 2.
'''
[[dependencies.exnihiloae]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[32,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.exnihiloae]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16, )"
    ordering="NONE"
    side="BOTH"
[[dependencies.exnihiloae]]
    modId="exnihilosequentia"
    mandatory=true
    versionRange="[1.16-1.4.0.0, )"
    ordering="AFTER"
    side="BOTH"
[[dependencies.exnihiloae]]
    modId="appliedenergistics2"
    mandatory=true
    versionRange="[8.1.0, )"
    ordering="AFTER"
    side="BOTH"
